spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true #To beautify or pretty print the SQL
      show_sql: true #show sql

  logging:
    level:
      org.hibernate:
        type.descriptor.sql: trace #show parameter binding
        SQL: DEBUG